export const defaultedges = [
    {
        id: "edge_1",
        label: "8",
        selected: false,
        source: "node_0",
        sourceHandle: null,
        target: "node_1",
        targetHandle: null,
    },
    {
        id: "edge_2",
        label: "22",
        selected: false,
        source: "node_1",
        sourceHandle: null,
        target: "node_3",
        targetHandle: null,
    },
    {
        id: "edge_3",
        label: "6",
        selected: false,
        source: "node_0",
        sourceHandle: null,
        target: "node_2",
        targetHandle: null,
    },
    {
        id: "edge_4",
        label: "20",
        selected: false,
        source: "node_2",
        sourceHandle: null,
        target: "node_4",
        targetHandle: null,
    },
    {
        id: "edge_5",
        label: "85",
        selected: false,
        source: "node_2",
        sourceHandle: null,
        target: "node_3",
        targetHandle: null,
    },
    {
        id: "edge_6",
        label: "18",
        selected: false,
        source: "node_1",
        sourceHandle: null,
        target: "node_5",
        targetHandle: null,
    },
    {
        id: "edge_7",
        label: "45",
        selected: false,
        source: "node_0",
        sourceHandle: null,
        target: "node_5",
        targetHandle: null,
    },
];
