export const defaultnodes = [
    {
        id: "node_0",
        type: "default",
        className: "StartNode",
        data: { label: "start", startNode: true },
        dragging: false,
        height: 26,
        position: { x: 262, y: -115 },
        selected: false,
        type: "default",
        width: 77,
    },
    {
        id: "node_1",
        type: "default",
        data: { label: "laba" },
        dragging: false,
        height: 26,
        position: { x: 346.25, y: -33.25 },
        selected: false,
        type: "default",
        width: 77,
    },
    {
        id: "node_2",
        type: "default",
        data: { label: "lee" },
        dragging: false,
        height: 26,
        position: { x: 185.25, y: -33.25 },
        selected: false,
        type: "default",
        width: 77,
    },
    {
        id: "node_3",
        type: "default",
        data: { label: "arya" },
        dragging: false,
        height: 26,
        position: { x: 389.75, y: 37.75 },
        selected: false,
        type: "default",
        width: 77,
    },
    {
        id: "node_4",
        type: "default",
        data: { label: "tiba" },
        dragging: false,
        height: 26,
        position: { x: 129.75, y: 48.75 },
        selected: false,
        type: "default",
        width: 77,
    },
    {
        id: "node_5",
        type: "default",
        data: { label: "carol" },
        dragging: false,
        height: 26,
        position: { x: 261.75, y: 105.25 },
        selected: false,
        type: "default",
        width: 77,
    },
];
