export const defaultnodes = [
    {
        id: "node_0",
        type: "default",
        className: "StartNode",
        data: { label: "start", startNode: true },
        dragging: false,
        height: 26,
        position: { x: 262, y: -115 },
        selected: false,
        width: 77,
    },
    {
        id: "node_1",
        className: "GoalNode",
        type: "default",
        data: { label: "1", startNode: true },
        dragging: false,
        height: 26,
        position: { x: 346.25, y: -33.25 },
        selected: false,
        width: 77,
    },
    {
        id: "node_2",
        type: "default",
        className: "",
        data: { label: "2" },
        dragging: false,
        height: 26,
        position: { x: 185.25, y: -33.25 },
        selected: false,
        width: 77,
    },
    {
        id: "node_3",
        type: "default",
        className: "",
        data: { label: "3" },
        dragging: false,
        height: 26,
        position: { x: 389.75, y: 37.75 },
        selected: false,
        width: 77,
    },
    {
        id: "node_4",
        type: "default",
        className: "",
        data: { label: "4" },
        dragging: false,
        height: 26,
        position: { x: 129.75, y: 48.75 },
        selected: false,
        width: 77,
    },
    {
        id: "node_5",
        type: "default",
        className: "",
        data: { label: "5", startNode: false },
        dragging: false,
        height: 26,
        position: { x: 261.75, y: 105.25 },
        selected: false,
        width: 77,
    },
];
